name: Node CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Clean target directory on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            shopt -s dotglob
            SSH_DIR="$HOME/.ssh"
            for item in ~/* ~/.??*; do
              if [[ "$item" != "$SSH_DIR" ]]; then
                echo "Removing: $item"
                rm -rf "$item"
              fi
            done
