name: Node CI

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Composer
        run: |
          sudo apt update
          sudo apt install -y curl php-cli unzip
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install PHP dependencies (phpdotenv)
        run: |
          composer install --no-dev --optimize-autoloader

      - name: List home directory contents
        run: ls -la ~/.composer
