name: Node CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v22.15.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Cache NPM and node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Run install task
        run: npm ci

      - name: Create .env
        run: |
          echo "HCAPTCHA_SITEKEY=${{ secrets.HCAPTCHA_SITEKEY }}" >> .env
          echo "FORM_ENDPOINT=${{ secrets.FORM_ENDPOINT }}" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
          echo "CATALOG_YML_URL=${{ secrets.CATALOG_YML_URL }}" >> .env

      - name: Inject Sitemap into robots.txt
        run: |
          echo "Sitemap: ${{ secrets.SITE_URL }}/sitemap.xml" >> robots.txt

      - name: Run build task
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
