name: Node CI

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v22.15.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Clean target directory on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ckseveql.beget.tech
          username: ckseveql_adm_lp
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            shopt -s dotglob
            HOME_DIR="${HOME:-$(eval echo ~)}"
            for item in "$HOME_DIR"/* "$HOME_DIR"/.??*; do
              if [[ "$item" != "$HOME_DIR/.ssh" ]]; then
                echo "Removing: $item"
                rm -rf "$item" || echo "Failed to remove $item"
              fi
            done
