name: Node CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Clean target directory on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ckseveql.beget.tech
          username: ckseveql_adm_lp
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            shopt -s dotglob
            for item in "$HOME"/* "$HOME"/.??*; do
              if [[ "$item" != "$HOME/.ssh" ]]; then
                echo "Removing: $item"
                rm -rf "$item"
              fi
            done
